## ---- ini, echo=FALSE, results='hide', message=FALSE, warning=FALSE------
# This chunk set the document environment, so it is hidden
library(knitr)
knitr::opts_chunk$set(fig.align="center",
                      message = FALSE, warning = FALSE, echo = TRUE, cache = FALSE)
options(width=50)
set.seed(1423)


## ----echo=FALSE, out.width='20%'-----------------------------------------
include_graphics('images/FLBEIA_logo.png')


## ---- eval=FALSE---------------------------------------------------------
## install.packages( c("FLCore", "FLFleet", "FLBEIA"),
##                   repos="http://flr-project.org/R")
## install.packages(c("r4ss","reshape2","arrayhelpers","dplyr","tidyr"))


## ---- pkgs, results = "hide"---------------------------------------------
library(FLBEIA)
library(r4ss)
library(reshape2)
library(arrayhelpers)
library(tidyr)
library(dplyr)


## ---- getfiles, message=FALSE--------------------------------------------
dir <- tempdir()
# download.file("http://www.flr-project.org/doc/src/ibPIL.zip", file.path(dir, "ibPIL.zip"))
# unzip(file.path(dir, "ibPIL.zip"), exdir=dir)
unzip("src/ibPIL.zip", exdir=dir)


## ---- loadibPIL----------------------------------------------------------
load(file.path(dir, "ibPIL.RData"))
ls()


## ---- checkData, eval=FALSE----------------------------------------------
## # Projection years
## main.ctrl
## 
## # Stock: one stock named as PIL with an age-structured population growth
## #        - recruitment: generated by a Beverton-Holt model fitted to historical data
## summary(biols)
## biols.ctrl
## summary(SRs)
## SRs$PIL@model
## SRs$PIL@params
## SRs$PIL@uncertainty
## 
## # Fleet: one unique fleet (INT), with one unique metier (ALL), targeting only sardine (PIL)
## #        - effort dynamics: simple mixed fisheries bechaviour
## #        - catch model    : Cobb Douglas at age
## #        - capital model  : fixed capital
## #        - price model    : fixed price
## summary(fleets)
## summary(fleets$INT@metiers)
## summary(fleets$INT@metiers$ALL@catches)
## fleets.ctrl
## 
## # Covariates: no covariates
## covars
## covars.ctrl
## 
## # Advice: TAC given by ICES HCR
## summary(advice)
## advice.ctrl
## 
## 
## # Indices: two indices available
## #          - AcousticNumberAtAge: numbers at age
## #          - DEPM               : total biomass every 3 years
## summary(indices)
## indices$AcousticNumberAtAge@index
## indices$AcousticNumberAtAge@index.q
## indices$DEPM@index
## indices$DEPM@index.q


## ----echo=TRUE, eval=TRUE------------------------------------------------
#########################################################
#### Function to read from FLstock object,
#### create SS3 files (from existing reference ones),
#### run ss3 assessment with new data, and
#### update FLR stock object with estimates from SS3.
#########################################################

########################################################
### Leire Citores september-october 2018 ###############
########################################################

ss32flbeia <- function(stock,indices,control,covars=covars){
  
  # save iteration number
  runi <- control$run_it
  
  # last year of the new stock object
  lasty <- range(stock)["maxyear"]
  
  # To avoid problems in SS3:
  # if catch < 10^-5 --> small value to total catch, 
  # remove catch at age (done some lines later),
  # and put the wt from year before. 
  stock@catch.wt[,which(is.na(stock@catch.wt[2,]))] <- stock@catch.wt[,ac(lasty-1)] 
  
  stock@catch <- computeCatch(stock)
  stock@catch[,which(stock@catch<10^-5)] <- 10^-5
  
  # print
  cat("catches in it", runi, range(stock)["maxyear"], "\n", 
      stock@catch[,ac(range(stock)["maxyear"])], "\n")
  
  # ref_name: reference ss3 assessment folder name
  ref_name <- control$ref_name
  
  # directory where the folder with the reference ss3 assessment is located
  assess_dir <- control$assess_dir
  
  # get current working directory
  dir0 <- getwd()
  
  # set the new working directory
  setwd(assess_dir)
  
  # create a new folder where the new assessment will be run
  dir <- paste0("assess_temp", runi, lasty)
  dir.create(dir)
  
  # copy the reference assessment folder  into the new folder
  file.copy(ref_name, dir, recursive = T)

  # set the working directory inside this folder
  # (at the end of the assessment this new folder will be deleted,
  #  but the reference assessment is always kept)
  temp_dir <- paste0(dir,paste0("/",ref_name))
  setwd(temp_dir)
  
  
  ################################################################
  #### read data from new FLR objects and write to SS3 files
  #################################################################

  # last year of the new stock object
  lasty <- range(stock)["maxyear"]

  # read reference assessment data file
  datss <- SS_readdat("sardine.dat", verbose = FALSE)

  ##control file
  ctl <- readLines("sardine.ctl")

  # natural mortality vector
  ctl[27] <- paste(m(stock)[,1],collapse=" ")
  # - update the year in the control file (from reference assessment year to actual year)
  ctl_new <- gsub(pattern = ac(datss$endyr), replace = ac(lasty), x = ctl)
  # - update the year recruitmen devs (assessment year-1)
  ctl_new <- gsub(pattern = ac(datss$endyr-1), replace = ac(lasty-1), x = ctl_new)
  # - write the new control file, it overwrites the old one
  writeLines(ctl_new, con="sardine.ctl")
  
  # total catch
  catch <- melt(catch(stock)[,])[,c("value","year")]
  catch$seas <- 1
  colnames(catch) <- colnames(datss$catch)
  datss$catch <- catch

  # age structured catch and index
  
  catchn <- dcast(na.omit(melt(catch.n(stock)[,])[,c("value","year","age")]),year~age)
  catchn <- cbind(catchn[,1],subset(datss$agecomp,FltSvy==1)[1,2:9],catchn[,-1])
  lastrow <- dim(catchn)[1]
  # no catch at age for the last year available (--> delete this value)
  catchn <- catchn[-lastrow,]
  # remove catch at age when catch<10^-4
  catch0years <- which(catchn[,ac(4)]<10^-4)
  if(length(catch0years)>0)
    catchn <- catchn[-catch0years,]
  # set manullay sample size for catch.n for years > 1990
  # sample size = 50 for year <= 1990
  # sample size = 75 for year > 1990
  # (see Iberian sardine Stock Annex for details)
  catchn[,"Nsamp"][catchn[,1]>1990] <- 75 
  
  indexn <- dcast(na.omit(melt(indices[[1]]@index[,])[,c("value","year","age")]),year~age)
  indexn <- cbind(indexn[,1],subset(datss$agecomp,FltSvy==2)[1,2:9],indexn[,-1])
  colnames(indexn) <- colnames(catchn)<-colnames(datss$agecomp)
  agecomp <- rbind(catchn,indexn)
  datss$agecomp <- agecomp

  # biomass indices
  
  index2  <- cbind(indexn[,1],rowSums(indexn[,c(10:16)]))
  se_log2 <- subset(datss$CPUE,index==2)$se_log
  index2  <- cbind(year=index2[,1],seas=1,index=2,obs=index2[,2],se_log=mean(se_log2))

  index3  <- na.omit(melt(indices[[2]]@index[,])[,c("value","year")])
  se_log3 <- subset(datss$CPUE,index==3)$se_log[1]
  index3  <- cbind(year=index3$year,seas=1,index=3,obs=index3$value,se_log=se_log3)

  datss$CPUE <- as.data.frame(rbind(index2,index3))

  ################################################################################

  #number of lines
  datss$styr  <- min(catch$year)
  datss$endyr <- an(lasty)
  datss$N_catch   <- dim(datss$catch)[1]
  datss$N_cpue    <- dim(datss$CPUE)[1]
  datss$N_agecomp <- dim(datss$agecomp)[1]

  #write the new data file, it overwrites the old one
  SS_writedat(datss,"sardine.dat", overwrite = T, verbose = FALSE)
  
  ##wtatage file
  #stock weight (fleet=0)
  stockwt <- t(stock.wt(stock)[,,drop=T])
  stockwt <- cbind(rownames(stockwt),1,1,1,1,0,stockwt)
  stockwt <- apply(stockwt,1,function(x){paste(x,collapse="\t")})
  names(stockwt) <- NULL

  # weigth for age structured acoustic index (fleet=2) (same as stock weight)
  index2wt <- t(stock.wt(stock)[,,drop=T])
  index2wt <- cbind(rownames(index2wt),1,1,1,1,2,index2wt)
  index2wt <- apply(index2wt,1,function(x){paste(x,collapse="\t")})
  names(index2wt) <- NULL

  # catch weight (fleet 1 and -1)
  catchwt <- t(catch.wt(stock)[,,drop=T])
  catchwt <- cbind(rownames(catchwt),1,1,1,1,1,catchwt)
  catchwt <- apply(catchwt,1,function(x){paste(x,collapse="\t")})
  names(catchwt) <- NULL

  catchwt_1 <- t(catch.wt(stock)[,,drop=T])
  catchwt_1 <- cbind(rownames(catchwt_1),1,1,1,1,-1,catchwt_1)
  catchwt_1 <- apply(catchwt_1,1,function(x){paste(x,collapse="\t")})
  names(catchwt_1) <- NULL

  # maturity (fleet=-2)
  mat <- t((mat(stock)*stock.wt(stock))[,,drop=T])
  mat <- cbind(rownames(mat),1,1,1,1,-2,mat)
  mat <- apply(mat,1,function(x){paste(x,collapse="\t")})
  names(mat) <- NULL

  # read the reference weight file
  wta <- readLines("wtatage.ss")[1:7]
  # generate the new weigth matrix with the data from FLR objects
  wta_new <- c(wta,stockwt,catchwt,mat,catchwt_1,index2wt)
  # update number of lines
  wta_new[1] <- ac(length(wta_new)-length(wta))
  # write the new weight file, it overwrtites the old one
  writeLines(wta_new, con="wtatage.ss")
  
  
  ################################################################
  ##                        execute SS3
  ## (be careful to use the adecuate executable depending on the
  ##  operating system -windows, linux or ios-)
  ################################################################

  system('./SS3.exe')
  
  
  #####################################################
  ### S3 output back to FLR. Just harvest and stock:
  #####################################################

  dir.assess <- paste0(getwd(),"")
  assess  <- SS_output(dir = dir.assess, model = "ss3", forecast = FALSE, 
                       printstats = FALSE, verbose = FALSE, covar = FALSE)
  maxyear <- assess$endyr
  ages    <- assess$agebins
  years   <- assess$startyr:assess$endyr
  
  #------------------------------------
  # extract assessment outputs:
  # F-AT-AGE, REFERENCE F
  #
  # we need to calculate F-at-age from apical F 
  # (i.e. F on the fully selected age) and 
  # selectivity at age
  #------------------------------------
  
  selectivity <- subset(assess$ageselex, fleet==1 & factor=="Asel2" & year %in% years, 
                        select=c("year", ac(ages)))

  idx <- grep("F_", assess$derived_quants$LABEL)
  f.apical <- data.frame(f=assess$derived_quants[idx,"Value"])
  f.apical$year <- years

  f.apsel <- merge(f.apical, selectivity, all.x = T,by="year")

  f <- f.apsel$f * f.apsel[,ac(ages)]

  harvest <- FLQuant(unname(as.matrix(t(f))),quant="age",units="f", 
                     dimnames=list(age=ac(ages), year=ac(years)))
  
  #------------------------------------
  # extract assessment outputs:
  # NUMBERS-AT-AGE
  #------------------------------------
  
  natage <- subset(assess$natage, Era=="TIME" & `Beg/Mid`=="B" , select=ac(ages))

  stock.n <- FLQuant(unname(as.matrix(t(natage))), quant='age', units='NA',
                     dimnames=list(age=ac(ages), year=ac(years)))
  
  # update stock object
  harvest(stock) <- harvest
  stock.n(stock) <- stock.n
  stock(stock)   <- computeStock(stock)
  
  # fill covars to see retros
  covars$ssb[ac(lasty),ac(years)]  <- ssb(stock)[,]
  covars$rec[ac(lasty),ac(years)]  <- rec(stock)[,]
  covars$fbar[ac(lasty),ac(years)] <- fbar(stock)[,]

  params <- assess$parameters
  q2 <- exp(subset(params,Label=="LnQ_base_2_Acoustic_survey")[,"Value"])
  q3 <- exp(subset(params,Label=="LnQ_base_3_DEPM_survey")[,"Value"])
  covars$qs[1,ac(lasty)] <- q2
  covars$qs[2,ac(lasty)] <- q3

  # Three selectivity periods - breakpoints at 1986 & 2004
  # (see Iberian sardine Stock Annex for details)
  covars$sel[,ac(lasty),3,,,] <- as.numeric(subset(selectivity,year==lasty)[1,-1])
  covars$sel[,ac(lasty),2,,,] <- as.numeric(subset(selectivity,year==2004)[1,-1]) 
  covars$sel[,ac(lasty),1,,,] <- as.numeric(subset(selectivity,year==1986)[1,-1])
  
  
  # CONVERGENCE
  
  covars$conv[,ac(lasty)]     <- assess$maximum_gradient_component
  
  
  #######################
  ### delete files
  #######################
  
  setwd(assess_dir)
  unlink(paste0(assess_dir,dir),recursive=T)
  
  #return to the original working directory
  setwd(dir0)

  return(list(stock = stock,covars=covars))
}



## ---- setAssCtrl---------------------------------------------------------
assess.ctrl <- list( PIL = list())

# Assessment model
assess.ctrl$PIL$assess.model <- "ss32flbeia"

# Does the assessment model work with iterations?
assess.ctrl$PIL$work_w_Iter <- FALSE

# Units for fishing mortality: f or hr
assess.ctrl$PIL$harvest.units <- "f"

# Assesment control arguments
sc <- "s0"; it <- 1
assess.ctrl$PIL$control <- list( ref_name = "assess_ref", 
                                 assess_dir =  file.path(dir,"ss3R/"),
                                 run_it = paste(it,"_sc",sc,sep=""))

# Assess output also for assessment year
assess.ctrl$PIL$ass.curryr <- TRUE


## ---- setCovars----------------------------------------------------------
ages      <- dimnames(biols[[1]]@n)$age
yrs       <- dimnames(biols[[1]]@n)$year
proj.yrs  <- ac(main.ctrl$sim.years[1]:main.ctrl$sim.years[2])
assini.yr <- ac(main.ctrl$sim.years[1]-1)

# Assessment estimates:
covars$ssb <- covars$fbar <- covars$rec <- 
  FLQuant(NA, dimnames=list(assess.year=c(assini.yr,proj.yrs), year=yrs))

# - ssb
covars$ssb[assini.yr,] <- ssb(biols$PIL)[,]

# - recruitment
covars$rec[assini.yr,] <- (biols$PIL@n)[1,]

# - survey catchabilities
covars$qs <- FLQuant(NA, dimnames = list(qs=c("acoustic","depm"), year=yrs))

# - selectivity at age
covars$sel <- FLQuant(NA, dimnames = list(age=ages, year=yrs,unit=1:3))

# Assessment convergence
covars$conv <- FLQuant(NA, dimnames = list(conv="conv",year=yrs))


## ---- helpObsCtrl, eval=FALSE--------------------------------------------
## ?create.obs.ctrl


## ---- setObsCtrl---------------------------------------------------------
flq.PIL <- FLQuant(dimnames = dimnames(biols$PIL@n)) 
obs.ctrl <- create.obs.ctrl( stksnames = "PIL", n.stks.inds = 2, 
                             stks.indsnames = names(indices$PIL),
                             stkObs.models = "age2ageDat", 
                             indObs.models = c("ageInd", "bioInd"), 
                             flq.PIL = flq.PIL)

# Required observation also for assessment year
obs.ctrl$PIL$obs.curryr <- TRUE


## ---- runFLBEIA----------------------------------------------------------
s0 <- FLBEIA( biols = biols, SRs = SRs, BDs = NULL, fleets = fleets,
              covars = covars, indices = indices, advice = advice,
              main.ctrl = main.ctrl, biols.ctrl = biols.ctrl, fleets.ctrl = fleets.ctrl,
              covars.ctrl = covars.ctrl, obs.ctrl = obs.ctrl,
              assess.ctrl = assess.ctrl, advice.ctrl = advice.ctrl)


## ---- sumPlot------------------------------------------------------------
# - stock summary
s0_bio <- bioSum(s0, scenario="hcrICES_assSS3")
plotbioSum( s0_bio, Blim=PIL_ref.pts[["Blim"]], Bpa=PIL_ref.pts[["Bpa"]], 
            proj.yr=main.ctrl$sim.years[["initial"]])

# - fleet summary
s0$fleets <- setUnitsNA(s0$fleets)
s0_flt <- fltSum(s0, scenario="hcrICES_assSS3")
plotfltSum( s0_flt, proj.yr=main.ctrl$sim.years[["initial"]])

# - risk summary
s0_risk  <- riskSum( s0, Bpa = c(PIL=PIL_ref.pts[["Bpa"]]), Blim = c(PIL=PIL_ref.pts[["Blim"]]), 
                     Prflim = c(INT = NA), 
                     scenario="hcrICES_assSS3")
s0_risk$year <- as.numeric(ac(s0_risk$year))
ggplot( data=s0_risk, aes(x=year, y=value, color=scenario)) +
  geom_line() +
  facet_wrap(~indicator, scales="free") +
  facet_grid(indicator ~ .) +
  geom_vline(xintercept = main.ctrl$sim.years[["initial"]]-1, linetype = "longdash")+
  theme_bw()+
  theme(text=element_text(size=15),
        title=element_text(size=15,face="bold"),
        strip.text=element_text(size=15))+
  ylab("Risk")


## ---- checkConv----------------------------------------------------------
# Number of years in which assessment did not converged
sum(s0$covars$conv>0.001,na.rm=T) 

# In case there are, let's see which one(s):
dimnames(s0$covars$conv)$year[!is.na(s0$covars$conv) & s0$covars$conv>0.01]


## ---- assOupts-----------------------------------------------------------
# Management Procedure - perceived
stk.MP <- s0$covars[c("rec", "fbar", "ssb", "qs")]
nyr <- dim(stk.MP$ssb)[1]
stk.MP <- lapply( stk.MP, function(x) x[-nyr,])

# Operating Model - "real"
stk.OM <- list()
stk.OM$ssb <- ssb(s0$biols$PIL)
stk.OM$rec <- s0$biols$PIL@n[1,]
#! +++ CREO QUE HAY UN LAG DE UN ANNO EN LO QUE GUARDADMOS!!!! +++
#!     --> COMPROBAR

stk.OM$indices <- stk.MP$qs*NA
stk.OM$indices[1,] <- quantSums(s0$indices$PIL$AcousticNumberAtAge@index)
stk.OM$indices[2,] <- s0$indices$PIL$DEPM@index


## ---- assRetros----------------------------------------------------------
dat <- stk.MP[c("ssb", "fbar", "rec")]

dat <- do.call("rbind", lapply(seq_along(dat), function(i,x) {
  cbind(as.data.frame(x[[i]]),indicator=names(x)[i])
}, x=dat))

ggplot( dat, aes( year, data, col = factor(assess.year), fill = factor(assess.year)))+
  facet_wrap(~indicator, scales = "free", ncol = 2) +
  stat_summary(fun.y = median,
               fun.ymin = function(x) quantile(x,0.05), 
               fun.ymax = function(x) quantile(x,0.95), 
               geom = "ribbon",alpha=0.1,col=NA) +
  stat_summary(fun.y = median,
               geom = "line",size=1) + 
  ggtitle("retros")


## ---- assPerf------------------------------------------------------------
dat <- as.data.frame(sweep( stk.MP$ssb, 2, stk.OM$ssb, "/"))
ggplot(dat,aes(year,data))+facet_wrap(~assess.year)+
  stat_summary(fun.y = median,
               fun.ymin = function(x) quantile(x,0.05), 
               fun.ymax = function(x) quantile(x,0.95), 
               geom = "ribbon",alpha=0.2,col=NA) +
  stat_summary(fun.y = median,
               geom = "line",size=1)+
  geom_hline(yintercept = 1)+geom_vline(xintercept = main.ctrl$sim.years[["initial"]]-1)+
  ggtitle("")+ylim(0.7,1.3)+ylab("estim ssb/real ssb")

dat <- as.data.frame(sweep( stk.MP$rec, 2, stk.OM$rec, "/"))
ggplot(dat,aes(year,data))+facet_wrap(~assess.year)+
  stat_summary(fun.y = median,
               fun.ymin = function(x) quantile(x,0.05), 
               fun.ymax = function(x) quantile(x,0.95), 
               geom = "ribbon",alpha=0.2,col=NA) +
  stat_summary(fun.y = median,
               geom = "line",size=1)+
  geom_hline(yintercept = 1)+geom_vline(xintercept = main.ctrl$sim.years[["initial"]]-1)+
  ggtitle("")+ylim(0.7,1.3)+ylab("estim rec/real rec")


dat <- as.data.frame(stk.MP$qs)
ggplot(dat,aes(year,data,col=factor(qs),fill=factor(qs)))+#facet_wrap(~assess.year)+
  stat_summary(fun.y = median,
               fun.ymin = function(x) quantile(x,0.05), 
               fun.ymax = function(x) quantile(x,0.95), 
               geom = "ribbon",alpha=0.1,col=NA) +
  stat_summary(fun.y = median,
               geom = "line",size=1)+
  geom_hline(yintercept = 1)+geom_vline(xintercept = main.ctrl$sim.years[["initial"]]-1)+
  ggtitle("")+ylab("qs")

dat <- as.data.frame(stk.OM$indices)
ggplot(dat,aes(year,data,col=factor(qs),fill=factor(qs)))+facet_wrap(~qs,scales="free")+
  stat_summary(fun.y = median,
               fun.ymin = function(x) quantile(x,0.05), 
               fun.ymax = function(x) quantile(x,0.95), 
               geom = "ribbon",alpha=0.1,col=NA) +
  stat_summary(fun.y = median,
               geom = "line",size=1)+
  geom_hline(yintercept = 1)+geom_vline(xintercept = main.ctrl$sim.years[["initial"]]-1)+
  ggtitle("")+ylab("generated indices")

dat <- as.data.frame(s0$covars$sel)
ggplot(dat,aes(age,data,col=factor(year),fill=factor(year)))+facet_wrap(~unit)+
  stat_summary(fun.y = median,
               fun.ymin = function(x) quantile(x,0.05), 
               fun.ymax = function(x) quantile(x,0.95), 
               geom = "ribbon",alpha=0.1,col=NA) +
  stat_summary(fun.y = median,
               geom = "line",size=1)+ 
  ggtitle("")+ylab("selectivities by block")

